### ISSUE TITLE
Include changelog

### ISSUE THREAD

**Issue by tbergq** [kiwicom/orbit-design-tokens#160]
Hi, it would be great if you could include a changelog, also please with some suggestions to which token to use when you remove a token. 

Thank you 😊

**Comment by vepor** [comment]
We use GitHub releases and temporary changelog. I've added suggestions to [`0.7.0`](https://github.com/kiwicom/orbit-design-tokens/releases/tag/v0.7.0) release where we deleted some tokens.
We will probably add generated changelog once we move this repository into `orbit` monorepo.

**Comment by tbergq** [comment]
Ok, I missed that, thank you 🙂
