### ISSUE TITLE
Product Light is not the correct value

### ISSUE THREAD

**Issue by rojcyk** [kiwicom/orbit-design-tokens#53]
Thanks to @tbergq I was able to find a bug regarding a product color light in our tokens specification. Currently, it seems like it is set to `#ff9999` (or at least the tests are). But reading orbit.kiwi, it should be `#E1F5F2`

But even that does not seem right, since this color is red. The result is still the same, the product light is not the right shade.

**Comment by rojcyk** [comment]
After some debugging, it seems like the `product.light` is set to `product.light.active`

**Comment by RobinCsl** [comment]
Searching for #e1f5f2 in the whole repository yielded nothing when this color is visible on
https://orbit.kiwi/visual-style/color/
with name Product Light. 

Could someone inquire further/fix this? Thanks

**Comment by wEprous** [comment]
Yep, the tests are - on purpose. I'll update this one color.
