### ISSUE TITLE
Add mediaquery breakpoints

### ISSUE THREAD

**Issue by tbergq** [kiwicom/orbit-design-tokens#80]
Just a suggestion, but would it be a good idea to keep this in `orbit-design-tokens` so we do not have to create this for every new project?

**Comment by wEprous** [comment]
Yep, it's a good idea and wanted to do it. It will be added when PR https://github.com/kiwicom/orbit-components/pull/820 be resolved

**Comment by wEprous** [comment]
| Name                                      | Value
| :--------------------------- | :--------------------- | 
| `widthMediaQueryMediumMobile` | `414`
| `widthMediaQueryLargeMobile` | `576`
| `widthMediaQueryTablet` | `768`
| `widthMediaQueryDesktop` | `992`
| `widthMediaQueryLargeDesktop` | `1200`
